mode = "dark"

accent = "#7aa2f7"
selection = "#2e3c64"
muted = "#565f89"

background = "#24283b"
dark_background = "#1f2335"
darker_background = "#1b1e2d"
lighter_background = "#292e42"

foreground = "#a9b1d6"
dark_foreground = "#565f89"
light_foreground = "#b4bee6"
bright_foreground = "#c0caf5"

red = "#f7768e"
yellow = "#e0af68"
orange = "#ff9e64"
green = "#9ece6a"
cyan = "#7dcfff"
blue = "#7aa2f7"
magenta = "#bb9af7"
brown = "#804f32"

bright_red = "#ff899d"
bright_yellow = "#faba4a"
bright_green = "#9fe044"
bright_cyan = "#a4daff"
bright_blue = "#8db0ff"
bright_magenta = "#c7a9ff"
