#!/usr/bin/env bash
#
# Make GTK4 apps follow the active Omarchy theme.
#
# READ THIS BEFORE RUNNING IT. Never run a script from the internet that you have
# not read. It writes two paths under your home directory:
#
#   ~/.config/omarchy/themed/gtk.css.tpl  palette template, re-rendered on every theme switch
#   ~/.config/gtk-4.0/gtk.css             symlink to the file Omarchy generates
#
# It refuses to overwrite either of them if something else is already there, and
# it is idempotent: running it twice does nothing the second time. Pass
# --uninstall to remove both.
#
# It never touches a running app. libadwaita reads the stylesheet at process
# start only, so quit Files yourself to see the new palette. Pass
# --auto-restart-files to install a theme-set hook that does that for you on
# every theme switch, at the cost of closing any Files window you have open.
#
# This is not part of the theme, and it is not specific to it. Omarchy does not
# theme GTK apps at all, so this follows whichever theme you switch to.
# libadwaita ignores the gtk-theme setting by design and draws its own palette,
# so overriding its named colors is the only supported way to recolor GTK4 apps.
# See omacom/omarchy#8408 for the upstream fix that should make this unnecessary.

set -euo pipefail

TPL="$HOME/.config/omarchy/themed/gtk.css.tpl"
GTK_CSS="$HOME/.config/gtk-4.0/gtk.css"
GENERATED="$HOME/.local/state/omarchy/current/theme/gtk.css"
HOOK="$HOME/.config/omarchy/hooks/theme-set.d/restart-files"

read -r -d '' TPL_BODY <<'GTKCSSTPL' || true
/* Generated by Omarchy from the active theme's colors.toml. Do not edit:
 * this file is rebuilt on every theme switch. Edit the template instead, at
 * ~/.config/omarchy/themed/gtk.css.tpl
 *
 * libadwaita ignores the gtk-theme setting by design. Overriding its named
 * colors here is the only supported way to recolor GTK4 apps, and it reaches
 * them only at process start, so a running app keeps its old palette until you
 * quit it. GTK3 cannot be recolored this way at all: the overrides are
 * provider-scoped and never reach the stock theme's own rules.
 *
 * Accent pairs follow Omarchy's own convention from vscode-theme.json.tpl,
 * which puts {{ background }} on top of {{ accent }}.
 */

@define-color window_bg_color {{ background }};
@define-color window_fg_color {{ foreground }};

/* Content surfaces: the file grid, list views, text areas. */
@define-color view_bg_color {{ dark_background }};
@define-color view_fg_color {{ foreground }};

@define-color headerbar_bg_color {{ lighter_background }};
@define-color headerbar_fg_color {{ foreground }};
@define-color headerbar_border_color {{ foreground }};
@define-color headerbar_backdrop_color {{ background }};
@define-color headerbar_shade_color {{ darker_background }};

@define-color sidebar_bg_color {{ dark_background }};
@define-color sidebar_fg_color {{ foreground }};
@define-color sidebar_backdrop_color {{ darker_background }};
@define-color sidebar_shade_color {{ darker_background }};
@define-color sidebar_border_color {{ darker_background }};

@define-color secondary_sidebar_bg_color {{ darker_background }};
@define-color secondary_sidebar_fg_color {{ foreground }};
@define-color secondary_sidebar_backdrop_color {{ darker_background }};
@define-color secondary_sidebar_shade_color {{ darker_background }};
@define-color secondary_sidebar_border_color {{ darker_background }};

@define-color card_bg_color {{ lighter_background }};
@define-color card_fg_color {{ foreground }};
@define-color card_shade_color {{ darker_background }};

@define-color dialog_bg_color {{ lighter_background }};
@define-color dialog_fg_color {{ foreground }};

@define-color popover_bg_color {{ lighter_background }};
@define-color popover_fg_color {{ foreground }};
@define-color popover_shade_color {{ darker_background }};

@define-color accent_bg_color {{ accent }};
@define-color accent_fg_color {{ background }};
@define-color accent_color {{ accent }};

@define-color destructive_bg_color {{ red }};
@define-color destructive_fg_color {{ background }};
@define-color destructive_color {{ red }};

@define-color success_bg_color {{ green }};
@define-color success_fg_color {{ background }};
@define-color success_color {{ green }};

@define-color warning_bg_color {{ yellow }};
@define-color warning_fg_color {{ background }};
@define-color warning_color {{ yellow }};

@define-color error_bg_color {{ red }};
@define-color error_fg_color {{ background }};
@define-color error_color {{ red }};

@define-color shade_color {{ darker_background }};
@define-color scrollbar_outline_color {{ darker_background }};
@define-color thumbnail_bg_color {{ dark_background }};
@define-color thumbnail_fg_color {{ foreground }};
GTKCSSTPL

read -r -d '' HOOK_BODY <<'GTKHOOK' || true
#!/bin/bash

# Written by install-gtk-theming.sh --auto-restart-files.
#
# libadwaita reads ~/.config/gtk-4.0/gtk.css at process start, and Files runs as
# a --gapplication-service daemon that outlives its windows, so a theme switch
# cannot reach one that is already running. It is D-Bus activatable and comes
# back on demand, so this costs an open window and nothing else.
#
# Cost: every open Files window closes on a theme switch, and an in-progress
# copy or move goes with it. Delete this file to stop that.

pkill -x nautilus 2>/dev/null

exit 0
GTKHOOK

die() {
  echo "error: $*" >&2
  exit 1
}

reapply_theme() {
  local theme
  theme=$(cat "$HOME/.local/state/omarchy/current/theme.name" 2>/dev/null || true)

  if [[ -z $theme ]] || ! command -v omarchy-theme-set >/dev/null; then
    echo "Switch theme once to apply the change."
    return
  fi

  echo "Re-applying '$theme' to generate the stylesheet..."
  omarchy-theme-set "$theme"
}

uninstall() {
  local removed=0

  if [[ -L $GTK_CSS && $(readlink "$GTK_CSS") == "$GENERATED" ]]; then
    rm -f "$GTK_CSS"
    echo "removed $GTK_CSS"
    removed=1
  elif [[ -e $GTK_CSS ]]; then
    echo "left $GTK_CSS alone: it is not the symlink this script made"
  fi

  if [[ -f $TPL ]]; then
    rm -f "$TPL"
    echo "removed $TPL"
    removed=1
  fi

  if [[ -f $HOOK ]]; then
    if [[ $(<"$HOOK") == "$HOOK_BODY" ]]; then
      rm -f "$HOOK"
      echo "removed $HOOK"
      removed=1
    else
      echo "left $HOOK alone: it is not the file this script wrote"
    fi
  fi

  (( removed )) || { echo "Nothing to uninstall."; return; }

  reapply_theme

  cat <<'DONE'

Done. GTK apps use libadwaita's own colors again.

Restart Files to drop the theme. This closes every Files window you have open:

  pkill -x nautilus
DONE
}

AUTO_RESTART=0

case "${1:-}" in
  "") ;;
  --auto-restart-files) AUTO_RESTART=1 ;;
  --uninstall) uninstall; exit 0 ;;
  *) die "unknown argument '$1' (--auto-restart-files, --uninstall)" ;;
esac

# Anything already at these paths belongs to someone else. Refuse rather than
# guess, unless it is byte-identical to what this script writes, which makes a
# second run a no-op.
tpl_needed=1
link_needed=1
hook_needed=$AUTO_RESTART

if (( hook_needed )) && [[ -e $HOOK ]]; then
  [[ -f $HOOK && $(<"$HOOK") == "$HOOK_BODY" ]] ||
    die "$HOOK already exists and differs. Move it aside first."
  hook_needed=0
fi

if [[ -e $TPL ]]; then
  [[ -f $TPL && $(<"$TPL") == "$TPL_BODY" ]] ||
    die "$TPL already exists and differs. Move it aside first."
  tpl_needed=0
fi

if [[ -L $GTK_CSS ]]; then
  [[ $(readlink "$GTK_CSS") == "$GENERATED" ]] ||
    die "$GTK_CSS is a symlink somewhere else. Move it aside first."
  link_needed=0
elif [[ -e $GTK_CSS ]]; then
  die "$GTK_CSS already exists. Move it aside first, or add '@import' yourself."
fi

if (( tpl_needed == 0 && link_needed == 0 && hook_needed == 0 )); then
  echo "Already installed. Nothing to do."
  exit 0
fi

cat <<INFO
This will create:

  $TPL
  $GTK_CSS -> $GENERATED
INFO

if (( AUTO_RESTART )); then
  cat <<INFO
  $HOOK

Then it re-applies your current theme to generate the stylesheet. From then on
the hook restarts Files on every theme switch, closing any window you have open.

INFO
else
  cat <<'INFO'

Then it re-applies your current theme to generate the stylesheet. Nothing you
have running is touched, so quit Files yourself before opening it again.

INFO
fi

mkdir -p "$(dirname "$TPL")" "$(dirname "$GTK_CSS")"

(( tpl_needed )) && printf '%s\n' "$TPL_BODY" >"$TPL" && echo "wrote $TPL"
(( link_needed )) && ln -sfn "$GENERATED" "$GTK_CSS" && echo "linked $GTK_CSS"

if (( hook_needed )); then
  mkdir -p "$(dirname "$HOOK")"
  printf '%s\n' "$HOOK_BODY" >"$HOOK"
  chmod +x "$HOOK"
  echo "wrote $HOOK"
fi

reapply_theme

cat <<'DONE'

Done.

Known limits:
  - A running app keeps the palette it started with. Files runs as a daemon
    that outlives its windows, so closing the window is not enough.
  - GTK3 apps are not covered and cannot be fixed this way.
  - Light themes get a poor accent foreground: accent_fg_color is the theme's
    background, which is right for dark themes and wrong for light ones.
  - Re-run with --uninstall to remove everything this added.
DONE

if (( AUTO_RESTART )); then
  cat <<DONE

Files restarts itself on every theme switch from now on, closing any window you
have open. Stop that with:

  rm $HOOK
DONE
else
  cat <<'DONE'

Restart Files to apply the theme. This closes every Files window you have open:

  pkill -x nautilus

Or re-run with --auto-restart-files to have that done on every theme switch.
DONE
fi
